-- =====================================================================
-- AUTH v6 — troca de e-mail com CÓDIGO enviado ao e-mail ATUAL.
-- Nada é alterado sem: (1) senha atual + (2) código de 6 dígitos que
-- chega no e-mail já cadastrado. Tabela inacessível pela aplicação —
-- só a Edge Function (service role) escreve e lê.
-- =====================================================================
begin;

create table if not exists public.trocas_email (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  email_atual  citext not null,
  email_novo   citext not null,
  codigo_hash  text not null,
  tentativas   int not null default 0,
  expira_em    timestamptz not null,
  confirmado_em timestamptz,
  cancelado    boolean not null default false,
  created_at   timestamptz not null default now()
);
alter table public.trocas_email enable row level security;
-- sem policy: invisível para authenticated/anon. Só service role (Edge Function).

create index if not exists idx_trocas_email_user on public.trocas_email (user_id, created_at desc);

-- registro de segurança das ações sensíveis da conta
create table if not exists public.log_seguranca (
  id         bigint primary key generated by default as identity,
  user_id    uuid references auth.users(id) on delete set null,
  evento     text not null,
  detalhe    jsonb not null default '{}'::jsonb,
  ip         text,
  created_at timestamptz not null default now()
);
alter table public.log_seguranca enable row level security;

drop policy if exists log_seguranca_proprio on public.log_seguranca;
create policy log_seguranca_proprio on public.log_seguranca
  for select to authenticated using (user_id = auth.uid());
drop policy if exists log_seguranca_admin on public.log_seguranca;
create policy log_seguranca_admin on public.log_seguranca
  for select to authenticated using (public.papel_atual() = 'admin');

commit;
